# Power
std_msgs/Header header # timestamp is the time the
         	       # field was measured
              	       # frame_id is the location and orientation
              	       # of the field measurement

std_msgs/Int64 voltage48
std_msgs/Int64 voltage12
std_msgs/Int64 voltage8_2
std_msgs/Int64 voltage8_1
std_msgs/Int64 voltage6_2
std_msgs/Int64 voltage6_1

std_msgs/Int64 load48
std_msgs/Int64 load12
std_msgs/Int64 load8_2
std_msgs/Int64 load8_1
std_msgs/Int64 load6_2
std_msgs/Int64 load6_1

