/*
 * File: left_in_right.c
 *
 * MATLAB Coder version            : 2.8
 * C/C++ source code generated on  : 27-May-2016 09:27:58
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "left_in_right.h"
#include "right_in_left.h"
#include "rdivide.h"

/* Function Definitions */

/*
 * LEFT_IN_RIGHT
 *     S = LEFT_IN_RIGHT(Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12)
 * Arguments    : double q1
 *                double q2
 *                double q3
 *                double q4
 *                double q5
 *                double q6
 *                double q7
 *                double q8
 *                double q9
 *                double q10
 *                double q11
 *                double q12
 *                double S[16]
 * Return Type  : void
 */
void left_in_right(double q1, double q2, double q3, double q4, double q5, double
                   q6, double q7, double q8, double q9, double q10, double q11,
                   double q12, double S[16])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t10;
  double t11;
  double t13;
  double t14;
  double t15;
  double t16;
  double t17;
  double t18;
  double t19;
  double t23;
  double t27;
  double t31;
  double t32;
  double t33;
  double t36;
  double t39;
  double t43;
  double t44;
  double t45;
  double t47;
  double t50;
  double t54;
  double t55;
  double t56;
  double t58;
  double t61;
  double t62;
  double t66;
  double t69;
  double t70;
  double t71;
  double t72;
  double t76;
  double t79;
  double t82;
  double t85;
  double t88;
  double t90;
  double t92;
  double t96;
  double t99;
  double t100;
  double t104;
  double t107;
  double t112;
  double t115;
  double t118;
  double t123;
  double t127;
  double t129;
  double t132;
  double t135;
  double t137;
  double t138;
  double t139;
  double t147;
  double t143;
  double t146;
  double t148;
  double t149;
  double t151;
  double t152;
  double t155;
  double t159;
  double t163;
  double t166;
  double t167;
  double t168;
  double t171;
  double t173;
  double t176;
  double t178;
  double t193;
  double t180;
  double t183;
  double t186;
  double t189;
  double t230;
  double t229;
  double t192;
  double t197;
  double t201;
  double t204;
  double t205;
  double t207;
  double t208;
  double t212;
  double t213;
  double t210;
  double t211;
  double t216;
  double t219;
  double t222;
  double t225;
  double t228;
  double t232;
  double t234;
  double t236;
  double t238;
  double x[16];

  /*     This function was generated by the Symbolic Math Toolbox version 6.2. */
  /*     25-May-2016 12:24:50 */
  q1 = -q1;
  q2 = -q2;
  q3 = -q3;
  q4 = -q4;
  q5 = -q5;
  q6 = -q6;
  q7 = -q7;
  q8 = -q8;
  q9 = -q9;
  q10 = -q10;
  q11 = -q11;
  q12 = -q12;
  t2 = cos(q7);
  t3 = cos(q9);
  t4 = sin(q7);
  t5 = sin(q8);
  t6 = sin(q9);
  t7 = cos(q10);
  t10 = t2 * t3 + t4 * t5 * t6;
  t11 = sin(q10);
  t13 = t2 * t6 - t3 * t4 * t5;
  t14 = cos(q3);
  t15 = sin(q3);
  t16 = cos(q4);
  t17 = sin(q4);
  t18 = cos(q5);
  t19 = sin(q5);
  t23 = rdivide(1.0, t16 * t16 + t17 * t17);
  t27 = rdivide(1.0, t18 * t18 + t19 * t19);
  t31 = rdivide(1.0, t14 * t14 + t15 * t15);
  t32 = cos(q1);
  t33 = sin(q1);
  t36 = t16 * t19 * t23 * t27 + t17 * t18 * t23 * t27;
  t39 = t16 * t18 * t23 * t27 + -(t17 * t19 * t23 * t27);
  t43 = rdivide(1.0, t32 * t32 + t33 * t33);
  t44 = cos(q2);
  t45 = sin(q2);
  t47 = t15 * t31 * t36 - t14 * t31 * t39;
  t50 = t14 * t31 * t36 + t15 * t31 * t39;
  t54 = rdivide(1.0, t44 * t44 + t45 * t45);
  t55 = sin(q11);
  t56 = cos(q11);
  t58 = t3 * t4 - t2 * t5 * t6;
  t61 = t4 * t6 + t2 * t3 * t5;
  t62 = cos(q8);
  t66 = t7 * t13 + t10 * t11;
  t69 = t7 * t10 - t11 * t13;
  t70 = t55 * t66 - t56 * t69;
  t71 = cos(q6);
  t72 = sin(q6);
  t76 = rdivide(1.0, t71 * t71 + t72 * t72);
  t79 = t16 * t18 * t23 * t27 * t72 * t76 + -(t17 * t19 * t23 * t27 * t72 * t76);
  t82 = t16 * t19 * t23 * t27 * t72 * t76 + t17 * t18 * t23 * t27 * t72 * t76;
  t85 = t3 * t11 * t62 + t6 * t7 * t62;
  t88 = t3 * t7 * t62 - t6 * t11 * t62;
  t90 = t56 * t85 + t55 * t88;
  t92 = t14 * t31 * t79 - t15 * t31 * t82;
  t96 = t7 * t61 + t11 * t58;
  t99 = t7 * t58 - t11 * t61;
  t100 = t55 * t96 - t56 * t99;
  t104 = t45 * t54 * t92 + -(t44 * t54 * t71 * t76);
  t107 = t15 * t31 * t79 + t14 * t31 * t82;
  t112 = t16 * t19 * t23 * t27 * t71 * t76 + t17 * t18 * t23 * t27 * t71 * t76;
  t115 = t16 * t18 * t23 * t27 * t71 * t76 + -(t17 * t19 * t23 * t27 * t71 * t76);
  t118 = t15 * t31 * t112 - t14 * t31 * t115;
  t123 = t14 * t31 * t112 + t15 * t31 * t115;
  t127 = t45 * t54 * t118 + -(t44 * t54 * t72 * t76);
  t129 = t18 * t27 * t71 * t76 * 0.1055 + 0.28;
  t132 = t17 * t23 * t129 + t16 * t19 * t23 * t27 * t71 * t76 * 0.1055;
  t135 = (t16 * t23 * t129 + t17 * t19 * t23 * t27 * t71 * t76 * -0.1055) + 0.28;
  t137 = t15 * t31 * t132 - t14 * t31 * t135;
  t138 = t62 * 0.096;
  t139 = t2 * 0.088;
  t147 = t4 * -0.02;
  t143 = t138 + t5 * (t139 - (-t147));
  t146 = t2 * 0.02 + t4 * 0.088;
  t148 = t6 * t146;
  t149 = t139 + t147;
  t151 = t138 + t5 * t149;
  t152 = t3 * t146;
  t155 = t14 * t31 * t132 + t15 * t31 * t135;
  t159 = t45 * t54 * t137 + t44 * t54 * t72 * t76 * -0.1055;
  t163 = t33 * t43 * t47 + t32 * t43 * t45 * t50 * t54;
  t166 = t32 * t43 * t47 + -(t33 * t43 * t45 * t50 * t54);
  t167 = sin(q12);
  t168 = cos(q12);
  t171 = t55 * t99 + t56 * t96;
  t173 = t167 * t171 - t2 * t62 * t168;
  t176 = t32 * t43 * t104 + t33 * t43 * t107;
  t178 = t55 * t85;
  t193 = t56 * t88;
  t180 = t5 * t168 - t167 * (t178 - t193);
  t183 = t44 * t54 * t92 + t45 * t54 * t71 * t76;
  t186 = t55 * t69 + t56 * t66;
  t189 = t167 * t186 + t4 * t62 * t168;
  t230 = -(t33 * t43 * t104);
  t229 = t32 * t43 * t107;
  t192 = -t230 + -t229;
  t197 = t44 * t54 * t118 + t45 * t54 * t72 * t76;
  t201 = t33 * t43 * t123 + -(t32 * t43 * t127);
  t204 = t32 * t43 * t123 + t33 * t43 * t127;
  t205 = t7 * 0.28;
  t207 = t148 + t3 * t151;
  t208 = t7 * t207;
  t212 = t6 * t151;
  t213 = t152 - t212;
  t210 = (t205 + t208) + t11 * t213;
  t211 = t11 * 0.28;
  t216 = (t32 * t43 * t155 + t33 * t43 * t159) + 0.02;
  t219 = (t32 * t43 * t159 + -(t33 * t43 * t155)) + 0.088;
  t222 = (t44 * t54 * t137 + t45 * t54 * t72 * t76 * 0.1055) - 0.096;
  t225 = t168 * t171 + t2 * t62 * t167;
  t228 = t5 * t167 + t168 * (t178 - t193);
  t232 = t168 * t186 - t4 * t62 * t167;
  t234 = t56 * 0.28;
  t236 = (t211 + t11 * t207) - t7 * t213;
  t238 = t5 * 0.096 - t62 * t149;
  x[0] = (t70 * t166 + t100 * t163) + t44 * t50 * t54 * t90;
  x[1] = (-t163 * t173 - t166 * t189) - t44 * t50 * t54 * t180;
  x[2] = (t163 * t225 + t166 * t232) - t44 * t50 * t54 * t228;
  x[3] = 0.0;
  x[4] = (t70 * t192 - t90 * t183) - t100 * t176;
  x[5] = (t173 * t176 + t180 * t183) - t189 * t192;
  x[6] = (-t232 * (t229 + t230) - t176 * t225) + t183 * t228;
  x[7] = 0.0;
  x[8] = (t70 * t204 - t90 * t197) + t100 * t201;
  x[9] = (-t173 * t201 + t180 * t197) - t189 * t204;
  x[10] = (t197 * t228 + t201 * t225) + t204 * t232;
  x[11] = 0.0;
  x[12] = ((((t55 * 0.28 + t55 * t210) - t70 * t216) + t90 * t222) + t100 * t219)
    + t56 * ((t211 + t11 * (t148 + t3 * t143)) - t7 * (t152 - t6 * t143));
  x[13] = (((-(t167 * ((t234 + t56 * t210) - t55 * t236)) - t173 * t219) - t180 *
            t222) + t189 * t216) - t168 * t238;
  x[14] = ((((-(t167 * t238) + t219 * t225) - t216 * t232) - t222 * t228) + t168
           * ((t234 - t55 * t236) + t56 * ((t205 + t208) + t11 * (t152 - t212))))
    + 0.1055;
  x[15] = 1.0;
  memcpy(&S[0], &x[0], sizeof(double) << 4);
}

/*
 * File trailer for left_in_right.c
 *
 * [EOF]
 */
