/*
 * File: right_in_left.c
 *
 * MATLAB Coder version            : 2.8
 * C/C++ source code generated on  : 27-May-2016 09:27:58
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "left_in_right.h"
#include "right_in_left.h"
#include "rdivide.h"

/* Function Definitions */

/*
 * RIGHT_IN_LEFT
 *     S = RIGHT_IN_LEFT(Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12)
 * Arguments    : double q1
 *                double q2
 *                double q3
 *                double q4
 *                double q5
 *                double q6
 *                double q7
 *                double q8
 *                double q9
 *                double q10
 *                double q11
 *                double q12
 *                double S[16]
 * Return Type  : void
 */
void right_in_left(double q1, double q2, double q3, double q4, double q5, double
                   q6, double q7, double q8, double q9, double q10, double q11,
                   double q12, double S[16])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t10;
  double t11;
  double t13;
  double t14;
  double t15;
  double t16;
  double t17;
  double t18;
  double t19;
  double t23;
  double t27;
  double t31;
  double t32;
  double t33;
  double t36;
  double t39;
  double t43;
  double t44;
  double t45;
  double t47;
  double t50;
  double t54;
  double t55;
  double t56;
  double t58;
  double t61;
  double t62;
  double t66;
  double t69;
  double t70;
  double t71;
  double t72;
  double t76;
  double t79;
  double t82;
  double t85;
  double t88;
  double t90;
  double t92;
  double t96;
  double t99;
  double t100;
  double t104;
  double t107;
  double t112;
  double t115;
  double t118;
  double t123;
  double t127;
  double t129;
  double t132;
  double t135;
  double t137;
  double t138;
  double t146;
  double t140;
  double t144;
  double t145;
  double t148;
  double t149;
  double t152;
  double t156;
  double t160;
  double t163;
  double t164;
  double t165;
  double t168;
  double t170;
  double t173;
  double t175;
  double t190;
  double t177;
  double t180;
  double t183;
  double t186;
  double t227;
  double t226;
  double t189;
  double t194;
  double t198;
  double t201;
  double t204;
  double t207;
  double t210;
  double t213;
  double t214;
  double t215;
  double t219;
  double t222;
  double t225;
  double t229;
  double t233;
  double t240;
  double x[16];

  /*     This function was generated by the Symbolic Math Toolbox version 6.2. */
  /*     25-May-2016 12:23:45 */
  q1 = -q1;
  q2 = -q2;
  q3 = -q3;
  q4 = -q4;
  q5 = -q5;
  q6 = -q6;
  q7 = -q7;
  q8 = -q8;
  q9 = -q9;
  q10 = -q10;
  q11 = -q11;
  q12 = -q12;
  t2 = cos(q1);
  t3 = cos(q3);
  t4 = sin(q1);
  t5 = sin(q2);
  t6 = sin(q3);
  t7 = cos(q4);
  t10 = t2 * t3 + t4 * t5 * t6;
  t11 = sin(q4);
  t13 = t2 * t6 - t3 * t4 * t5;
  t14 = cos(q9);
  t15 = sin(q9);
  t16 = cos(q10);
  t17 = sin(q10);
  t18 = cos(q11);
  t19 = sin(q11);
  t23 = rdivide(1.0, t16 * t16 + t17 * t17);
  t27 = rdivide(1.0, t18 * t18 + t19 * t19);
  t31 = rdivide(1.0, t14 * t14 + t15 * t15);
  t32 = cos(q7);
  t33 = sin(q7);
  t36 = t16 * t19 * t23 * t27 + t17 * t18 * t23 * t27;
  t39 = t16 * t18 * t23 * t27 + -(t17 * t19 * t23 * t27);
  t43 = rdivide(1.0, t32 * t32 + t33 * t33);
  t44 = cos(q8);
  t45 = sin(q8);
  t47 = t15 * t31 * t36 - t14 * t31 * t39;
  t50 = t14 * t31 * t36 + t15 * t31 * t39;
  t54 = rdivide(1.0, t44 * t44 + t45 * t45);
  t55 = sin(q5);
  t56 = cos(q5);
  t58 = t3 * t4 - t2 * t5 * t6;
  t61 = t4 * t6 + t2 * t3 * t5;
  t62 = cos(q2);
  t66 = t7 * t13 + t10 * t11;
  t69 = t7 * t10 - t11 * t13;
  t70 = t55 * t66 - t56 * t69;
  t71 = cos(q12);
  t72 = sin(q12);
  t76 = rdivide(1.0, t71 * t71 + t72 * t72);
  t79 = t16 * t18 * t23 * t27 * t72 * t76 + -(t17 * t19 * t23 * t27 * t72 * t76);
  t82 = t16 * t19 * t23 * t27 * t72 * t76 + t17 * t18 * t23 * t27 * t72 * t76;
  t85 = t3 * t11 * t62 + t6 * t7 * t62;
  t88 = t3 * t7 * t62 - t6 * t11 * t62;
  t90 = t56 * t85 + t55 * t88;
  t92 = t14 * t31 * t79 - t15 * t31 * t82;
  t96 = t7 * t61 + t11 * t58;
  t99 = t7 * t58 - t11 * t61;
  t100 = t55 * t96 - t56 * t99;
  t104 = t45 * t54 * t92 + -(t44 * t54 * t71 * t76);
  t107 = t15 * t31 * t79 + t14 * t31 * t82;
  t112 = t16 * t19 * t23 * t27 * t71 * t76 + t17 * t18 * t23 * t27 * t71 * t76;
  t115 = t16 * t18 * t23 * t27 * t71 * t76 + -(t17 * t19 * t23 * t27 * t71 * t76);
  t118 = t15 * t31 * t112 - t14 * t31 * t115;
  t123 = t14 * t31 * t112 + t15 * t31 * t115;
  t127 = t45 * t54 * t118 + -(t44 * t54 * t72 * t76);
  t129 = t18 * t27 * t71 * t76 * 0.1055 + 0.28;
  t132 = t17 * t23 * t129 + t16 * t19 * t23 * t27 * t71 * t76 * 0.1055;
  t135 = (t16 * t23 * t129 + t17 * t19 * t23 * t27 * t71 * t76 * -0.1055) + 0.28;
  t137 = t15 * t31 * t132 - t14 * t31 * t135;
  t138 = t2 * 0.02;
  t146 = t4 * -0.088;
  t140 = t138 - (-t146);
  t144 = t2 * 0.088 + t4 * 0.02;
  t145 = t62 * 0.096 - t5 * t144;
  t148 = t3 * t145;
  t149 = t138 + t146;
  t152 = t14 * t31 * t132 + t15 * t31 * t135;
  t156 = t45 * t54 * t137 + t44 * t54 * t72 * t76 * -0.1055;
  t160 = t33 * t43 * t47 + t32 * t43 * t45 * t50 * t54;
  t163 = t32 * t43 * t47 + -(t33 * t43 * t45 * t50 * t54);
  t164 = sin(q6);
  t165 = cos(q6);
  t168 = t55 * t99 + t56 * t96;
  t170 = t164 * t168 - t2 * t62 * t165;
  t173 = t32 * t43 * t104 + t33 * t43 * t107;
  t175 = t55 * t85;
  t190 = t56 * t88;
  t177 = t5 * t165 - t164 * (t175 - t190);
  t180 = t44 * t54 * t92 + t45 * t54 * t71 * t76;
  t183 = t55 * t69 + t56 * t66;
  t186 = t164 * t183 + t4 * t62 * t165;
  t227 = -(t33 * t43 * t104);
  t226 = t32 * t43 * t107;
  t189 = -t227 + -t226;
  t194 = t44 * t54 * t118 + t45 * t54 * t72 * t76;
  t198 = t33 * t43 * t123 + -(t32 * t43 * t127);
  t201 = t32 * t43 * t123 + t33 * t43 * t127;
  t204 = (t32 * t43 * t152 + t33 * t43 * t156) + 0.02;
  t207 = (-(t32 * t43 * t156) + t33 * t43 * t152) + 0.088;
  t210 = t148 + t6 * t149;
  t213 = t6 * t145 - t3 * t149;
  t214 = (t7 * 0.28 + t7 * t210) - t11 * t213;
  t215 = t11 * 0.28;
  t219 = (t44 * t54 * t137 + t45 * t54 * t72 * t76 * 0.1055) - 0.096;
  t222 = t165 * t168 + t2 * t62 * t164;
  t225 = t5 * t164 + t165 * (t175 - t190);
  t229 = t165 * t183 - t4 * t62 * t164;
  t233 = t5 * 0.096 + t62 * t144;
  t240 = (t56 * 0.28 + t56 * t214) - t55 * ((t215 + t7 * t213) + t11 * t210);
  x[0] = (t70 * t163 + t100 * t160) + t44 * t50 * t54 * t90;
  x[1] = (-t160 * t170 - t163 * t186) - t44 * t50 * t54 * t177;
  x[2] = (t160 * t222 + t163 * t229) - t44 * t50 * t54 * t225;
  x[3] = 0.0;
  x[4] = (t70 * t189 - t90 * t180) - t100 * t173;
  x[5] = (t170 * t173 + t177 * t180) - t186 * t189;
  x[6] = (-t229 * (t226 + t227) - t173 * t222) + t180 * t225;
  x[7] = 0.0;
  x[8] = (t70 * t201 - t90 * t194) + t100 * t198;
  x[9] = (-t170 * t198 + t177 * t194) - t186 * t201;
  x[10] = (t194 * t225 + t198 * t222) + t201 * t229;
  x[11] = 0.0;
  x[12] = ((((t55 * 0.28 + t55 * t214) - t70 * t204) - t100 * t207) + t90 * t219)
    + t56 * ((t215 - t7 * (t3 * t140 - t6 * t145)) + t11 * (t148 + t6 * t140));
  x[13] = (((t170 * t207 + t186 * t204) - t177 * t219) - t165 * t233) - t164 *
    t240;
  x[14] = ((((-(t164 * t233) + t165 * t240) - t207 * t222) - t204 * t229) - t219
           * t225) + 0.1055;
  x[15] = 1.0;
  memcpy(&S[0], &x[0], sizeof(double) << 4);
}

/*
 * File trailer for right_in_left.c
 *
 * [EOF]
 */
